# Generated by Django 4.0.5 on 2022-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog_review_alter_order_receive_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='Mehjabin@dreamgirl.com', max_length=254),
        ),
    ]
