# Generated by Django 4.0.5 on 2022-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Mehjabin chowdhury', max_length=50),
        ),
    ]
